#+STARTUP: indent content 
* My Configuration / Tools I use


* OS
 
I use [[http://releases.ubuntu.com/18.04/][Ubuntu 18.04 LTS]] as my primary development/work desktop of my main
computer, as my principle concern is stability and reliability rather
than bleeding edge software releases - my computer is my work-tool. I do
not have the time to waste fixing broken configuration packages after a
system update and have more important things to do on my work machine...
At the moment I am using the proprietary Radeon graphics drivers as the
open-source drivers for the 5700XT are still pretty bleeding edge at the
moment (December 2019), but hope to migrate to the full open stack next
year (probably will have happened by the time Ubuntu migrates to 19.04
as the LTS release).

I have no general complaints as =apt= works extremely well and so far
nothing has broken in months of use/upgrades, and Ubuntu is as close as
you get to an 'industry standard' in terms of Linux desktop computing
and software support.

I tend to use [[https://www.archlinux.org/][Arch Linux]] on my laptops due to the cleanliness and
efficiency of the =pacman= package manager, quality of the
documentation, and minimalism of the entire system, though the rolling release
nature of the distribution is somewhat annoying for machines that are
only used infrequently as so many packages change even within a short
period of time. I have also installed the [[https://archlinuxarm.org/][ARM architecture]] version of
Arch Linux on my old Chromebook running off an SD card which makes that
device 1000 times more usable than in its default stock state, limited
as a Google thin-client device. In fact, the completely fanless/silent
nature of the device, together with its full ALSA support for external
USB DAC audio device, means that it makes a brilliant high-end audio
device (for use with headphones or otherwise).

I have installed Lubuntu on my mother's laptop, though Xubuntu may well
be the better choice now.
 
Meanwhile on my main desktop, I have Windows 10 (for using a few
unsupported devices under Linux and other practical purposes; I rarely
use it though), Xubuntu 19.10, and [[https://www.freebsd.org/][FreeBSD 12]] installed under
[[https://virtualbox.org/][VirtualBox]]. I absolutely adore FreeBSD and think it has an unmatched
purity of design together with pretty much unbeatable stability.
Performance is also exceptional too. The one huge problem is the lack of
graphics drivers for recent hardware. This is a pity, as it actually
makes a superb desktop system with a bit of configuration, even though
its primary audience is the server market.

I am also very impressed with the latest release of the [[https://getfedora.org/][Fedora
Workstation]], in particular its =dnf= package manager, and may possibly
switch at some point, and will probably choose a minimal custom install
and work from there.
 
* Open Source Software

I use a wide range of FOSS; here is a shortlist of my most commonly used
applications.

I prefer to use [[https://www.firefox.org][Firefox]] as my main web-browser, with [[https://wiki.mozilla.org/Trusted_Recursive_Resolver][Trusted
Recursive Resolver]] enabled for DNS-over-HTTPS, Firefox's maximum tracking
protection enabled, and with [[https://addons.mozilla.org/en-US/firefox/addon/umatrix/][umatrix]], [[https://addons.mozilla.org/en-US/firefox/addon/https-everywhere][HTTPS everywhere]], [[https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/][uBlock Origin]] and [[https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/][Privacy
Badger]] add-ons enabled.

I also occasionally use [[https://www.chromium.org/Home][Chromium]] as some sites play better with Blink
engine based browsers.

** Editors

- [[https://www.gnu.org/software/emacs/][Emacs]] or more specifically, [[https://www.spacemacs.org/][Spacemacs]] (with evil-mode/vi enabled). An
  absolutely essential tool; I use org-mode for organising, planning, my
  calendar, for documentation, and document production; I use emacs for
  coding, as my IDE, and also for file management. Spacemacs just
  bundles this altogether in a very conveient bundle, though Emacs
  purists may object and want to write their own config file from
  scratch... ;-)  The Emacs window manager [[https://github.com/ch11ng/exwm][EXWM]] is also brilliant,
  though I tend to use [[https://xmonad.org/][Xmonad]] as my
  daily driver.

- [[https://www.vim.org/][Vim]], [[https://neovim.io/vim][Neovim]], are my goto's, though in effect I use them within Emacs.
  [[https://spacevim.org/][Spacevim]] is also a blazingly fast and impressive lean IDE.

- [[https://www.eclipse.org/][Eclipse]] IDE is pretty much an industry standard, and for good reason;
  incredibly powerful refactoring and support for many languages.
  Invaluable for Java development. Naturally I use it with the [[https://marketplace.eclipse.org/content/vrapper-vim][Vrapper]]
  vim plugin ;-)

- [[https://www.kdevelop.org/][KDevelop]] is an extremely nice and powerful IDE, though best suited for
  C/C++ coding.

- [[https://www.nano-editor.org/][GNU Nano]] is also nice for smaller editing tasks, and should
  probably be the default for most distro's as =vi= is quite cryptic for
  the non-initated... :-)

- [[https://atom.io][Atom]] is gorgeous to look and use, but is horrifically slow, and laggy
  even on high-end hardware due to its use of an Electron editing
  canvas. The niggling performance limitations meant that I eventually
  dropped it and committed to learing Emacs instead (which is ultimately
  more powerful anyway). It really could do with being rewritten using a
  native windowing canvas in C++ or similar, it would then be an
  exceptional editor.

Sublime editor is proprietary hence why it is not one of my preferred
options, though by all accounts it is like Atom but addresses its
performance issues since it is a native C++ application.

** File Management

I alternate between [[https://kde.org/plasma-desktop][KDE Plasma]] and [[https://xmonad.org][Xmonad]] as my main desktop/WM (Xmonad
most of the time, KDE when I fancy a bit of eye-candy), so consequently
I will sometimes use Dolphin, the Plasma default, but a lot of time I
prefer to work from the terminal. For serious tasks I usually use
[[https://doublecmd.sourceforge.io/][Double Commander]], and I have come to prefer [[https://vifm.info/][Vifm]] (Vi file manager) over
its fellow =vi= inspired "competitor" [[https://ranger.github.io/][Ranger]].


** Graphics

- I have been using [[http://dia-installer.de/][Dia]] for a very long time. Essential and very easy to
  use vector editor for all manner of diagrams and flowcharts etc.

- [[https://www.gimp.org/][Gimp]] is another "open-source industry standard", and in many ways a
  Photoshop "killer". Is overkill for a lot of tasks though.

- [[http://kolourpaint.org/][Kolourpaint]] and [[http://mtpaint.sourceforge.net/][mtpaint]] are extremely convenient for quick and simple
  edits, for which Gimp represents overkill.

- I intend to get back into playing around with 3D rendering using
  [[https://www.blender.org/][Blender]] sometime. Probably one of the most impressive open source
  applications ever created.

** Office & Productivity

As mentioned above, I prefer to use [[https://orgmode.org/][Org-mode]] within Emacs for the
production of most documents from a plain-text basis. However:

- I use [[https://www.libreoffice.org/][LibreOffice]] as my mainstay office application for presentations
  and spreadsheets etc. Apart from the fact that it is FOSS, I actually
  much prefer it to Microsoft Office anyway; I don't see what it is
  lacking compared to any commercial rival. Fantastic program.

- [[https://www.latex-project.org/][LaTeX]] offers unparalleled quality of typesetting/output, though
  again, my go-to these days would be to type as much as possible/most of
  it in =org-mode=, then export to LaTeX, and only do final adjustments
  (as necessary) then, since the LaTeX syntax is not very pleasant to
  write in and involves a lot of boilerplate code for even basic
  documents. Fortunately the LaTeX export engine from org-mode is
  exceptionally good. This gives you virtually all of the benefits of
  LaTeX whilst also giving you plain-text minimal =org-mode= markup.

- [[http://freeplane.sourceforge.net/][Freeplane]] is also one of my all-time favourite programs. It is
  an incredibly powerful mind-mapping application. Mindmaps have
  advantages that no linear notes have, and I quite frequently use
  mind-mapping for the production of complex notes or thinking.

- I used to use [[https://www.mindforger.com/][Mindforger]] a lot, until eventually org-mode took
  over that role since it is ultimately a fully integrated solution. But
  Mindforger is a brilliant and easy to use non-linear note taking app
  with a gentle learning curve and very fast interface.

- A similar case exists for [[https://www.taskcoach.org/][Task Coach]], a very handy time tracking
  and project management/to-do application; but once again, ultimately
  org-mode replaced it.

** System & utilities

As mentioned before, I tend to use my own heavily customised Xmonad
setup with very "vi" keybindings and various custom shortcuts as my
window manager (and with a custom drop-down terminal), or KDE Plasma
(with [[https://kde.org/applications/system/org.kde.yakuake][Yakuake]] drop-down terminal). I also like [[https://cinnamon-spices.linuxmint.com/][Cinnamon]], for its
simplicity, [[https://www.gnome.org/][GNOME]] for its quirkiness/minimalism, and [[https://joewing.net/projects/jwm/][JWM]] for its
staggeringly light footprint (brilliant for weaker hardware/limited RAM
setups; Xmonad is also incredibly memory efficient) and intuitive 
configurability via a straightforward XML file (Xmonad is definitely not
so straightforward with its Haskell based configuration). [[https://xfce.org/][XFCE]] has also
turned into a nice and very efficient desktop too. But Xmonad (mainly)
and KDE are my mainstays.

I use [[https://bluesabre.org/projects/catfish/][Catfish]] for its powerful but very easy file searching, and [[https://github.com/BurntSushi/ripgrep][ripgrep]]
and [[https://github.com/junegunn/fzf][fzf]] for their powerful console based fuzzy finding capabilities.

I tend to use [[https://github.com/davatorium/rofi][rofi]] (instead of the better known [[https://tools.suckless.org/dmenu/][dmenu]]) as my file
launcher/window switcher under Xmonad, together with a few extensions,
but my favourite option is the lesser well known [[https://sourceforge.net/projects/synapse/][synapse]] project, which
uses the zeitgeist file indexing service. This makes it incredibly fast
for launching all manner of applications directly opening any file with
its associated application with just a few keystrokes from anywhere in
the desktop; much faster than using a "Start" menu or equivalent. KDE
has krunner built-in, but it still doesn't match synapse in overall
power.

For terminals, I use konsole when under KDE, but my favourite option is
the "power users" favourite, [[http://software.schmorp.de/pkg/rxvt-unicode.html][urxvt]] (i.e. rxvt-unicode) specifically
running in daemon mode for maximum speed/efficiency, with my own custom
=.Xresources= file to set up all the colours and properties just how I
like it.

I have a custom prompt set via my =.bashrc=. I also think that [[https://github.com/andreafrancia/trash-cli][trash-cli]]
should be considered an essential tool that anyone that uses the console
heavily should get into the habit of using. You only need one careless
slip with =rm -fr= and you could put yourself in serious difficulties!
(i.e. if you accidentally type =rm =fr /home/foo/* . tar.gz= you will
end up destroying /everything/ under =/home/foo= rather than just
deleting all the =tar.gz= files, due to the unintended space inserted
after the =*=...). By using suitable aliases in your =.bashrc= you soon
get into the habit of using =trash-put= to delete files instead. The
files are then still recoverable if you have made a mistake.
=trash-empty= removes them forever.

"I am careful... It has never happened to me."

One mistake, just one in thousands of commands, typed a bit too quickly,
that's all it could take, and you had better hope you have a very recent
backup... ;-)
