#!/bin/bash

CONF_DIR=~/.secretary
CONF_FILE=$CONF_DIR/secretaryrc
MASTER_LIST=$CONF_DIR/master.files
FILE_OPS_DIR=$CONF_DIR/fileops

#echo "master: $MASTER_LIST"

find "$1" -type f -exec file {} \; >> $MASTER_LIST

# Build the filelists, parsing the configuration file line-by-line
while read LINE 
do
	COMMENT_HASH="`echo $LINE | cut -c 1`"

	[ "$COMMENT_HASH" = "#" ] && continue

	TYPE_FIELD="`echo $LINE | cut -d ':' -f 1`"
	EXT_FIELD="`echo $LINE | cut -d ':' -f 2`"  
	DEST_FIELD="`echo $LINE | cut -d ':' -f 3`"

	# Process a file extension line by filename
	if [ "$TYPE_FIELD" = "ext" ]; then


		for EXT in $EXT_FIELD
		do
			echo "# -> [ \*.$EXT files ] " > "$CONF_DIR/filelist-$EXT.files"
			PRC_LINE=`cut -d ':' -f 1 "$MASTER_LIST" \
				| grep ".*/*\.$EXT$" | cut -z -c 1- | tr -d '\0'`
			
			if [ ! -z "$PRC_LINE" ]; then
				echo "\"$PRC_LINE\":\"$DEST_FIELD\"" >> "$CONF_DIR/filelist-$EXT.files"
			fi 
		done

	fi

	# Process a MIME type line using file
	if [ "$TYPE_FIELD" = "mime" ]; then
		for MIME in $EXT_FIELD
		do
			echo "# -> [ $MIME files ] " > "$CONF_DIR/filelist-$MIME.files"
			grep ": $MIME" "$MASTER_LIST" \
			| cut -d ':' -f 1 | awk -v b="\"" -v a="$DEST_FIELD" '/$/{ print b$0b":"b a b }' \
			>> "$CONF_DIR/filelist-$MIME.files"
		done
	fi

done < $CONF_FILE

# Remove the filelists with no files to copy
for FILELIST in `ls $CONF_DIR/filelist-*.files`
do
	if [ "`wc -l $FILELIST | cut -d ' ' -f 1`" -eq 1 ]; then
		rm $FILELIST
	fi
done

# Build the final copying script
TIMESTAMP="`date +%Y-%m-%d-%H_%M`"
echo "#!/bin/bash" > $FILE_OPS_DIR/file-operations-$TIMESTAMP.log

read -d '' FILE_HEADER_TXT << "ENDHEADER"
# ---------------------------------------------------------------
# ---------------------------------------------------------------
#
#        [ File operations list generated by secretary ] 
#
# ===============================================================
# ===============================================================
# 
# PLEASE look through this file carefully BEFORE running it
# to ensure that it will copying/moving the correct files to 
# your intended destination. 
# 
# ---------------- YOU HAVE BEEN WARNED!!!!! --------------------
# 
# To execute this script:
#
#    $ secretary run #log#
#
# where "#log#" will be a file of the form
# file-operations-TIMESTAMP.log, for example:
#
#    $ secretary run file-operations-2019-10-03-14_04.log
# 
# (Here the file operations script was created on March 3rd
# 2019, at 14:04 in the afternoon.)
#
# Alternatively you can run it by simply redirecting it to
# bash, e.g.:
# 
#    $ bash < file-operations-2019-10-03-14_04.log
#
# ----------------------------------------------------------------
ENDHEADER

echo "$FILE_HEADER_TXT" >> $FILE_OPS_DIR/file-operations-$TIMESTAMP.log

for FILELIST in `ls $CONF_DIR/filelist-*.files`
do
	if [ -s "$FILELIST" ]; 
	then
		HEADER_FLAG=1
		while read FILE_LINE
		do
			if [ $HEADER_FLAG -eq 1 ]; then

				echo "" >> "$FILE_OPS_DIR/file-operations-$TIMESTAMP.log"
				echo "$FILE_LINE" >> "$FILE_OPS_DIR/file-operations-$TIMESTAMP.log"
				echo "" >> "$FILE_OPS_DIR/file-operations-$TIMESTAMP.log"
				HEADER_FLAG=0
				continue
			fi

			FILE="`echo $FILE_LINE | cut -d ':' -f 1`"
			DEST="`echo $FILE_LINE | cut -d ':' -f 2`"
			echo "cp $FILE $DEST" >> $FILE_OPS_DIR/file-operations-$TIMESTAMP.log
		
		done < $FILELIST
	else
		rm $FILELIST 
	fi
done

find "$CONF_DIR" -name "*.files" -delete
